In [ ]:
%pip install numpy

In [ ]:
import numpy as np

In [1]:
import numpy as np

arr1d = np.arange(1, 11)
print(arr1d)

[ 1  2  3  4  5  6  7  8  9 10]


In [2]:
import numpy as np

arr2d = np.random.randint(0, 10, size=(3, 3))
print(arr2d)

[[9 6 1]
 [7 5 4]
 [7 0 4]]


In [5]:
import numpy as np

arr1d = np.arange(1, 11)
print(arr1d)

print("Sum:", arr1d.sum())
print("Mean:", arr1d.mean())
print("Max:", arr1d.max())

arr2x = arr1d * 2
print("Multiply all elements by 2:", arr2x)

arr0 = arr1d.copy()
arr0[arr0 > 5] = 0
print("Replace all values greater than 5 with 0:", arr0)

[ 1  2  3  4  5  6  7  8  9 10]
Sum: 55
Mean: 5.5
Max: 10
Multiply all elements by 2: [ 2  4  6  8 10 12 14 16 18 20]
Replace all values greater than 5 with 0: [1 2 3 4 5 0 0 0 0 0]
